### ISSUE TITLE
Cannot Install Nuget Package

### ISSUE THREAD

**Issue by PapaQuackers** [xabre/xamarin-bluetooth-le#268]
Hello,

For some reason every time I try to install the Nuget package I get this error: 
Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	

## Steps to reproduce

1. Open a new Xamarin PCL project.

2. Attempt To Install Nuget package into everything.

## Expected behavior
Should install without issue and have access to library.

## Actual behavior
Receiving error message and not building.

### Crashlog
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.	Bluetooth.UWP			
Warning		The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'Bluetooth, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Bluetooth.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters) in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 220
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName) in /Users/builder/data/lanes/5147/c2a33d8e/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 160
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Bluetooth.Android			
Warning		obj\Debug\libraryprojectimports.cache does not exist. No Project Library Imports found	Bluetooth.Android			
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	Bluetooth.Android		1	Active
Error		Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
Warning		Cannot resolve Assembly or Windows Metadata file 'System.Runtime.dll'	Bluetooth.UWP	c:\users\paul\source\repos\Bluetooth\Bluetooth\Bluetooth.UWP\Bluetooth.UWP.csproj		
Warning		3: error: Error: No resource found that matches the given name: attr 'windowActionModeOverlay'.	Bluetooth.Android	c:\users\paul\source\repos\Bluetooth\Bluetooth\Bluetooth.Android\Resources\values\styles.xml		
Warning		3: error: Error: No resource found that matches the given name: attr 'colorAccent'.	Bluetooth.Android	c:\users\paul\source\repos\Bluetooth\Bluetooth\Bluetooth.Android\Resources\values\styles.xml		
Warning		3: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'.	Bluetooth.Android	c:\users\paul\source\repos\Bluetooth\Bluetooth\Bluetooth.Android\Resources\values\styles.xml		
Warning		2: error: Error: No resource found that matches the given name: attr 'colorAccent'.	Bluetooth.Android	c:\users\paul\source\repos\Bluetooth\Bluetooth\Bluetooth.Android\Resources\values\styles.xml		
Warning		1: error: Error: No resource found that matches the given name: attr 'windowNoTitle'.	Bluetooth.Android	c:\users\paul\source\repos\Bluetooth\Bluetooth\Bluetooth.Android\Resources\values\styles.xml		
Warning		1: error: Error: No resource found that matches the given name: attr 'windowActionBar'.	Bluetooth.Android	c:\users\paul\source\repos\Bluetooth\Bluetooth\Bluetooth.Android\Resources\values\styles.xml		
Warning		1: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.	Bluetooth.Android	c:\users\paul\source\repos\Bluetooth\Bluetooth\Bluetooth.Android\Resources\values\styles.xml		
Warning		1: error: Error: No resource found that matches the given name: attr 'colorPrimary'.	Bluetooth.Android	c:\users\paul\source\repos\Bluetooth\Bluetooth\Bluetooth.Android\Resources\values\styles.xml		
Warning		1: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.	Bluetooth.Android	c:\users\paul\source\repos\Bluetooth\Bluetooth\Bluetooth.Android\Resources\values\styles.xml		
```

## Configuration

**Version of the Plugin:** 5.3.1

**Platform:** Android 7.0 - API 24

**Device:** SM-G955U

**Comment by smsissuechecker** [comment]
Hi @PapaQuackers,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by flyingxu** [comment]
For PCL, please try profile259
