### ISSUE TITLE
UWP doesn't work

### ISSUE THREAD

**Issue by yshteinm** [xabre/xamarin-bluetooth-le#487]
I am running Windows 10 Pro
Version	10.0.18363 Build 18363
and Visual Studio 2019.

Running just created new Xamarin Forms app. It runs great on Android but on Windows app it crashes on the follow line.

`        public IBluetoothLE Ble { get; } = CrossBluetoothLE.Current;`

with an exception

```
System.NotImplementedException
  HResult=0x80004001
  Message=This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
  Source=Plugin.BLE
  StackTrace:
   at Plugin.BLE.CrossBluetoothLE.get_Current()
   at BT2.Bt2AppManager..ctor() in C:\Sandbox\BEMO\CrossApp\trunk\BT2\BT2\BT2\Bt2AppManager.cs:line 36
   at BT2.Bt2AppManager.get_Current() in C:\Sandbox\BEMO\CrossApp\trunk\BT2\BT2\BT2\Bt2AppManager.cs:line 25
   at BT2.Views.BT2ScanView.initDeviceList() in C:\Sandbox\BEMO\CrossApp\trunk\BT2\BT2\BT2\Views\BT2ScanView.xaml.cs:line 48
   at BT2.Views.BT2ScanView..ctor() in C:\Sandbox\BEMO\CrossApp\trunk\BT2\BT2\BT2\Views\BT2ScanView.xaml.cs:line 25
   at BT2.MainPage.InitializeComponent() in C:\Sandbox\BEMO\CrossApp\trunk\BT2\BT2\BT2\obj\Debug\netstandard2.0\MainPage.xaml.g.cs:line 22
   at BT2.MainPage..ctor() in C:\Sandbox\BEMO\CrossApp\trunk\BT2\BT2\BT2\MainPage.xaml.cs:line 16
   at BT2.App..ctor() in C:\Sandbox\BEMO\CrossApp\trunk\BT2\BT2\BT2\App.xaml.cs:line 13
   at BT2.UWP.MainPage..ctor() in C:\Sandbox\BEMO\CrossApp\trunk\BT2\BT2\BT2.UWP\MainPage.xaml.cs:line 24
```

Below is UWP settings:

![image](https://user-images.githubusercontent.com/11545901/109992852-abfa7f00-7cd9-11eb-9314-03a8b4585659.png)

**Comment by smsissuechecker** [comment]
Hi @yshteinm,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by bbhxwl** [comment]
I can't run either
