### ISSUE TITLE
UWP  StartUpdatesAsync() throws error

### ISSUE THREAD

**Issue by lightway82** [xabre/xamarin-bluetooth-le#513]
I'm trying to subscribe to characteristic. LightBlue app subscribe correctly.

This code works correctly on android.

An error occurs after call   StartUpdatesAsync()

```
         ICharacteristic characteristic;

        private async void Button_Connect_OnClicked(object sender, EventArgs e)
        {
            if(_adapter.IsScanning) return;
            if (Device.RuntimePlatform == Device.Android)
            {
                if (!await PermissionsGrantedAsync())
                {
                    await DisplayAlert("Permission required", "Application needs location permission", "OK");
                    return;
                }  
            }

          
            try
            {         

                var device = await _adapter.ConnectToKnownDeviceAsync(deviceID);
                var service = await device.GetServiceAsync(Guid.Parse("0000ffe0-0000-1000-8000-00805f9b34fb"));
                characteristic = await service.GetCharacteristicAsync(Guid.Parse("0000ffe4-0000-1000-8000-00805f9b34fb"));
                 
                characteristic.ValueUpdated += (o, args) =>
                {
                    var bytes = args.Characteristic.Value;
                    MainThread.BeginInvokeOnMainThread(() =>
                    {
                        DebugText.Text = String.Join("", bytes);
                    });
                };
                await Task.Delay(1000);
                await characteristic.StartUpdatesAsync();
                await Task.Delay(1000);
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception);
                ErrorField.Text = exception.ToString();
            }

        }

```

## Steps to reproduce
Use Vanilla plugin

1. Connect

2. Get service

3. Get characteristic with "Notify" access type

4. Subscribe to characteristic 

## Expected behavior
Receive data by subscribe

## Actual behavior
Throw error

### Crashlog

System.Exception: [StartUpdatesNativeAsync] failed with status: Unreachable   
 at Plugin.BLE.Extensions.GattResultExtensions.ThrowIfError(GattCommunicationStatus status, String tag, Nullable`1 protocolError)
at Plugin.BLE.Extensions.GattResultExtensions.ThrowIfError(GattWriteResult result, String tag) 
at Plugin.BLE.UWP.Characteristic.StartUpdatesNativeAsync()

## Configuration

**Version of the Plugin:** Plugin.BLE 2.2.0-pre2

**Platform:** UWP

**Device:** Windows 10 Desktop 20H2  19042.928

**Comment by smsissuechecker** [comment]
Hi @lightway82,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by stsln** [comment]
Is there any progress on this error?
